name: Wake up Streamlit App

on:
  schedule:
    - cron: "0 */12 * * *" # Berjalan setiap 10 jam
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Pinging the Streamlit app
        run: |
          curl -I "https://airise-bot.streamlit.app"
